# Create a Personal Access Token (Tokens- Classic) from your personal account [Select these scopes: repo and admin:org]
# Paste the access token in the org repo [Secrets and variables > Actions]. Create a new variable named "BACKUP_TOKEN" in Repository secrets under Secrets tab

name: Dated Backup Repository

on:
  # Runs on pushes to main branch
  push:
    branches: [ main ]
  # Manual trigger
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: Folks-of-Devx/expenseTracker
          fetch-depth: 0 # Clone with complete history

      - name: Generate timestamp
        id: timestamp
        env:
          TZ: 'Asia/Kolkata'
        run: echo "timestamp=$(date +'%Y-%m-%d_%I-%M-%S_%p')" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
      - name: Create backup with timestamp
        env:
          TOKEN: ${{ secrets.BACKUP_TOKEN }}
          TIMESTAMP: ${{ steps.timestamp.outputs.timestamp }}
        run: |
          # Clone backup repository from personal GitHub account
          git clone https://$TOKEN@github.com/ritaban06/expenseTracker-backup.git backup-repo
          
          # Create timestamped directory
          cd backup-repo
          mkdir -p "backups/$TIMESTAMP"
          
          # Copy all files except .git and backup-repo
          cd ..
          rsync -av --exclude='.git' --exclude='backup-repo' ./ "backup-repo/backups/$TIMESTAMP/"
          
          # Commit and push changes
          cd backup-repo
          git add .
          git commit -m "Backup created on $TIMESTAMP"
          git push origin main
      - name: Cleanup
        run: |
          rm -rf backup-repo
      - name: Create backup summary
        run: |
          echo "Backup created successfully" >> $GITHUB_STEP_SUMMARY
          echo "Timestamp: ${{ steps.timestamp.outputs.timestamp }}" >> $GITHUB_STEP_SUMMARY
