name: Expo PR Preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Expo + EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Publish preview update with EAS
        id: eas-update
        run: |
          BRANCH="${{ github.head_ref }}"
          OUTPUT=$(eas update --branch $BRANCH --non-interactive --auto --json)
          echo "$OUTPUT" > eas_output.json

          PROJECT_ID=$(echo "$OUTPUT" | jq -r '.[0].projectId')
          GROUP_ID=$(echo "$OUTPUT" | jq -r '.[0].group')

          PREVIEW_URL="https://expo.dev/preview/update?projectId=$PROJECT_ID&group=$GROUP_ID"
          echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT


      - name: Comment on PR with Preview Link
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 **EAS Update Preview is Ready!**

            📲 Open the link in your browser:
            🔗 [Preview Update Link](${{ steps.eas-update.outputs.preview_url }})

            > ⚠️ JavaScript-only update using `eas update`. No native code rebuild.
