name: Expo PR Preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Expo + EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Publish preview update with EAS
        id: eas-update
        run: |
          # Fetch the source branch of the pull request
          BRANCH="${{ github.head_ref }}"
          eas update --branch $BRANCH --non-interactive --auto
          echo "https://expo.dev/preview/update?branchName=$BRANCH" > link.txt
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Comment on PR with Preview Link
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 **EAS Update Preview is Ready!**

            📲 Open the link below:
            🔗 [`https://expo.dev/preview/update?branchName=${{ github.head_ref }}`](https://expo.dev/preview/update?branchName=${{ github.head_ref }})

            > ⚠️ JavaScript-only update using `eas update`. No native code rebuild.
